blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/moonshadowrev/FCMPanel/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://moonshadowrev.github.io/FCMPanel/
    about: Check our comprehensive documentation and guides
  - name: 🔒 Security Issue
    url: https://github.com/moonshadowrev/FCMPanel/security/advisories/new
    about: Report security vulnerabilities privately (do not create public issues for security concerns)
  - name: 📧 Direct Contact
    url: mailto:moon.shadow.rev@gmail.com
    about: Contact the maintainer directly for sensitive matters 